# Generated by Django 5.2.5 on 2025-08-22 19:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('processo', models.CharField(blank=True, max_length=30)),
                ('pregao', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(choices=[('ENFERMAGEM', 'Enfermagem'), ('MEDICAMENTOS', 'Medicamentos')], max_length=20)),
                ('objeto', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('edital_vencedor', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='feriado',
            old_name='nome',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_item',
            field=models.CharField(default='SEM-CODIGO', max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='SEM-DESCRICAO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='edital_origem',
            field=models.CharField(default='SEM-EDITAL', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_item',
            field=models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('ENFERMAGEM', 'Enfermagem')], default='SEM-EDITAL', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ARPContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_arp', models.CharField(max_length=30)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='app_principal.edital')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='app_principal.fornecedor')),
            ],
            options={
                'unique_together': {('numero_arp', 'edital')},
            },
        ),
        migrations.CreateModel(
            name='ItemLicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(blank=True, max_length=50)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('centro_custo', models.CharField(blank=True, max_length=100)),
                ('proponente_codigo', models.CharField(blank=True, max_length=20)),
                ('proponente_nome', models.CharField(blank=True, max_length=255)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='app_principal.arpcontrato')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_principal.edital')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='app_principal.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50, unique=True)),
                ('data_pedido', models.DateField()),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('ATRASADO', 'Atrasado'), ('CONCLUIDO', 'Concluído')], max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.PositiveIntegerField()),
                ('quantidade_entregue', models.PositiveIntegerField(default=0)),
                ('status_entrega', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENTREGUE_PARCIAL', 'Entregue Parcial'), ('CONCLUIDO', 'Concluído')], max_length=20)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_principal.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_completo', models.CharField(max_length=255)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('setor', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_acao', models.CharField(max_length=100)),
                ('detalhes', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_principal.usuario')),
            ],
        ),
    ]
