# Generated by Django 5.2.5 on 2025-09-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_edital_empresa_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemlicitado',
            constraint=models.UniqueConstraint(fields=('codigo', 'edital'), name='unique_codigo_por_edital'),
        ),
    ]
