# Generated by Django 5.2.5 on 2025-09-09 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0003_itemlicitado_unique_codigo_por_edital'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('data_movimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('documento', models.CharField(blank=True, max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='app_principal.fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='app_principal.itemlicitado')),
            ],
            options={
                'ordering': ('-data_movimento', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo', to='app_principal.itemlicitado')),
            ],
        ),
    ]
