# Generated by Django 5.2.5 on 2025-09-12 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0004_movimentoestoque_saldoestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemlicitado',
            name='arquivo_nf',
            field=models.FileField(blank=True, null=True, upload_to='notas_fiscais/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='arquivo_nf',
            field=models.FileField(blank=True, null=True, upload_to='notas_fiscais/'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='arquivo_nf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='arquivo_nf_url_drive',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
